version: "2"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - ~/.pg/pg_data/base:/var/lib/postgresql/data
    env_file:
      - ./app/.env
    ports:
      - 5432:5432
  django_ex6:
    build: ./app
    container_name: work
    depends_on:
      - postgres
    volumes:
      - base_volume:/app/base
      - media_volume:/app/media
    env_file:
      - ./app/.env
    ports:
      - 8000:8000
    command: >
      bash -c " python manage.py migrate  && gunicorn -b 0.0.0.0:8000 parrotsite.wsgi:application"

volumes:
  base_volume:
  media_volume:
#  certs:
